spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE;
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: validate
  h2:
    console.enabled: true

logging:
  level:
    com: DEBUG
#    org: DEBUG